//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Descargas_NET.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:341985")]
        public string Api_WEBAPI_URL {
            get {
                return ((string)(this["Api_WEBAPI_URL"]));
            }
            set {
                this["Api_WEBAPI_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Api_WEBAPI_User {
            get {
                return ((string)(this["Api_WEBAPI_User"]));
            }
            set {
                this["Api_WEBAPI_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Api_WEBAPI_Password {
            get {
                return ((string)(this["Api_WEBAPI_Password"]));
            }
            set {
                this["Api_WEBAPI_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Api_WEBAPI_Token {
            get {
                return ((string)(this["Api_WEBAPI_Token"]));
            }
            set {
                this["Api_WEBAPI_Token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("apibentval/")]
        public string Api_WEBAPI_VirtualHost {
            get {
                return ((string)(this["Api_WEBAPI_VirtualHost"]));
            }
            set {
                this["Api_WEBAPI_VirtualHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int COM_MSCOMM_Puerto {
            get {
                return ((int)(this["COM_MSCOMM_Puerto"]));
            }
            set {
                this["COM_MSCOMM_Puerto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int COM_MSCOMM_BaudRate {
            get {
                return ((int)(this["COM_MSCOMM_BaudRate"]));
            }
            set {
                this["COM_MSCOMM_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Api_WEBAPI_AvisosActivos {
            get {
                return ((bool)(this["Api_WEBAPI_AvisosActivos"]));
            }
            set {
                this["Api_WEBAPI_AvisosActivos"] = value;
            }
        }
    }
}
